package io.agrest.backend.map;

/**
 * @author vyarmolovich
 * 10/24/18
 */
public interface DbAttribute {

    /**
     * Returns the SQL type of the column.
     *
     * @see java.sql.Types
     */
    int getType();

    String getName();

    boolean isMandatory();

    /**
     * Returns true if this column value is generated by the database. Other
     * terms for such columns are "auto-increment" or "identity".
     *
     * @since 1.2
     */
    boolean isGenerated();
}
